"""add Department

Revision ID: 216821d1d837
Revises: 01f081fbd32d
Create Date: 2024-07-05 01:31:55.481497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216821d1d837'
down_revision = '01f081fbd32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
